FROM golang:1.18 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY src/backend/backend.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o golang-backend .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/golang-backend .
COPY public/ public/
EXPOSE 8080
CMD ["./golang-backend"]